services:
  windows:
    build:
      context: ./
      target: ${WINDOWS_VM}
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - INSTALL_IDA=${INSTALL_IDA}
    platform: linux/amd64
    devices:
      - /dev/kvm
    volumes:
      - windows:/app/build
    ports:
      - "5912:5912"
    stop_signal: SIGKILL
