services:
  windows:
    build:
      context: ./
      target: ${WINDOWS_VM}
      args:
        - INSTALL_IDA_FREE=${INSTALL_IDA_FREE}
    platform: linux/amd64
    devices:
      - /dev/kvm
    volumes:
      - windows:/app/build
    ports:
      - "5912:5912"
    stop_signal: SIGKILL
