name: Build and Push Docker Image
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-buildx-action@master
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - uses: docker/build-push-action@master
      with:
        tags: |
          pwncollege/pwncollege_challenge:latest
          ghcr.io/pwncollege/pwncollege_challenge:latest
        file: containers/pwncollege_challenge/Dockerfile
        context: containers/pwncollege_challenge
        push: true
        cache-from: type=registry,ref=ghcr.io/pwncollege/pwncollege_challenge:latest
        cache-to: type=inline
